=== KPaulina/XML-schoolwork/classes3/Szablon-agencja.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT dokumenty_agencja (umowa,tabela,czas_obowiazywania,tabela_nieruchomosci,prowizja,agent_prowadzacy,podpis)>

<!ELEMENT umowa (numer,miejscowosc_zawarcia,data)>
<!ELEMENT numer (#PCDATA)>
<!ELEMENT miejscowosc_zawarcia (#PCDATA)>
<!ELEMENT data (#PCDATA)>

<!ELEMENT tabela (agencja,poszukujacy)>
<!ELEMENT agencja (nazwa_agencji,adres,NIP,REGON)>
<!ELEMENT nazwa_agencji (#PCDATA)>
<!ELEMENT adres (miasto,kod_pocztowy,ulica,numer_bud)>

<!ELEMENT poszukujacy (dane_osobowe,adres_poszukującego,PESEL,dowod)>
<!ELEMENT dane_osobowe (imie,nazwisko)>
<!ELEMENT imie (#PCDATA)>
<!ELEMENT nazwisko (#PCDATA)>

<!ELEMENT NIP (#PCDATA)>
<!ELEMENT REGON (#PCDATA)>

<!ELEMENT adres_poszukującego (miasto,kod_pocztowy,ulica,numer_bud,numer_lok)>
<!ELEMENT miasto (#PCDATA)>
<!ELEMENT kod_pocztowy (#PCDATA)>
<!ELEMENT ulica (#PCDATA)>
<!ELEMENT numer_bud (#PCDATA)>
<!ELEMENT numer_lok (#PCDATA)>

<!ELEMENT PESEL (#PCDATA)>
<!ELEMENT dowod (#PCDATA)>

<!ELEMENT czas_obowiazywania (obowiazuje_od,obowiazuje_do)>
<!ELEMENT obowiazuje_od (#PCDATA)>
<!ELEMENT obowiazuje_do (#PCDATA)>

<!ELEMENT tabela_nieruchomosci (lp+)>
<!ELEMENT lp (nieruchomosc,adres_nieruchomosci)>
<!ELEMENT nieruchomosc (typ_nieruchomosci,powierzchnia,dzialka)>
<!ELEMENT adres_nieruchomosci (miejscowosc, ulica_nieruchomosci, nr_budynku)>
<!ELEMENT typ_nieruchomosci (#PCDATA)>
<!ELEMENT powierzchnia (#PCDATA)>
<!ELEMENT dzialka (#PCDATA)>

<!ELEMENT miejscowosc (#PCDATA)>
<!ELEMENT ulica_nieruchomosci (#PCDATA)>
<!ELEMENT nr_budynku (#PCDATA)>


<!ELEMENT prowizja (procent)>
<!ELEMENT procent (#PCDATA)>

<!ELEMENT agent_prowadzacy (imie_agenta,nazwisko_agenta,telefon)>
<!ELEMENT imie_agenta (#PCDATA)>
<!ELEMENT nazwisko_agenta (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>

<!ELEMENT podpis (agencja_podpis,kupujacy_podpis)>
<!ELEMENT agencja_podpis (podpis_imie, podpis_nazwisko)>
<!ELEMENT podpis_imie (#PCDATA)>
<!ELEMENT podpis_nazwisko (#PCDATA)>

<!ELEMENT kupujacy_podpis (imie_kupującego,nazwisko_kupującego)>
<!ELEMENT imie_kupującego (#PCDATA)>
<!ELEMENT nazwisko_kupującego (#PCDATA)>

<!ATTLIST lp nr ID #REQUIRED >

=== KPaulina/XML-schoolwork/xml-agencja.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="apply.xsl"?>

<!DOCTYPE dokumenty_agencja SYSTEM "Szablon-agencja.dtd">
<dokumenty_agencja>
 	<umowa>
		<numer>5676</numer>
		<miejscowosc_zawarcia>Warszawa</miejscowosc_zawarcia>
		<data>2020-10-01</data>
	</umowa>
	
	<tabela>
		<agencja>
			<nazwa_agencji>Stoleczne Centrum Nierchomosci</nazwa_agencji>
			<adres>
				<miasto>Warszawa</miasto>
				<kod_pocztowy>01-042</kod_pocztowy>
				<ulica>ul.Okopowa</ulica>
				<numer_bud>56</numer_bud>
			</adres>
			
			<NIP>723-230-21-03</NIP>
			<REGON>567382911</REGON>
		</agencja>
		
		<poszukujacy>
			<dane_osobowe>
				<imie>Miroslaw</imie>
				<nazwisko>Strzalinski</nazwisko>
			</dane_osobowe>
			
			<adres_poszukującego>
				<miasto>Radzymin</miasto>
				<kod_pocztowy>05-250</kod_pocztowy>
				<ulica>ul. Koscielna</ulica>
				<numer_bud>12</numer_bud>
				<numer_lok>4</numer_lok>
			</adres_poszukującego>
			
			<PESEL>71091456340</PESEL>
			<dowod>DD 678844</dowod>
		</poszukujacy>
	</tabela>
	
	<czas_obowiazywania>
	 	<obowiazuje_od>2014-10-01></obowiazuje_od>
		<obowiazuje_do>2014-12-31</obowiazuje_do>
	</czas_obowiazywania>
	
	<tabela_nieruchomosci>
		<lp nr="id_001">
			<nieruchomosc>
				<typ_nieruchomosci>Dom wolnostojacy</typ_nieruchomosci>
				<powierzchnia>240</powierzchnia>
				<dzialka>1000</dzialka>
			</nieruchomosc>
					
			<adres_nieruchomosci>
				<miejscowosc>Podkowa Lesna</miejscowosc>
				<ulica_nieruchomosci>Kwiatowa</ulica_nieruchomosci>
				<nr_budynku>23</nr_budynku>
			</adres_nieruchomosci>
		</lp>
		
		<lp nr="id_002">
			<nieruchomosc>
				<typ_nieruchomosci>Segment</typ_nieruchomosci>
				<powierzchnia>200</powierzchnia>
				<dzialka>560</dzialka>
			</nieruchomosc>
					
			<adres_nieruchomosci>
				<miejscowosc>Milan�wek</miejscowosc>
				<ulica_nieruchomosci>Spokojna</ulica_nieruchomosci>
				<nr_budynku>7</nr_budynku>
			</adres_nieruchomosci>
		</lp>
		
		<lp nr="id_003">
			<nieruchomosc>
				<typ_nieruchomosci>Dom wolnostojacy</typ_nieruchomosci>
				<powierzchnia>260</powierzchnia>
				<dzialka>3500</dzialka>
			</nieruchomosc>
					
			<adres_nieruchomosci>
				<miejscowosc>Brwin�w</miejscowosc>
				<ulica_nieruchomosci>Cicha</ulica_nieruchomosci>
				<nr_budynku>12</nr_budynku>
			</adres_nieruchomosci>
		</lp>
	</tabela_nieruchomosci>
	
	<prowizja>
		<procent>3</procent>
	</prowizja>
	
	<agent_prowadzacy>
		<imie_agenta>Agnieszka</imie_agenta>
		<nazwisko_agenta>Kownacka</nazwisko_agenta>
		<telefon>22 755-24-76</telefon>
	</agent_prowadzacy>
	
	<podpis>
		<agencja_podpis>
			<podpis_imie>Agnieszka</podpis_imie>
			<podpis_nazwisko>Kownacka </podpis_nazwisko>
		</agencja_podpis>
		
		<kupujacy_podpis>
			<imie_kupującego>Miroslaw</imie_kupującego>
			<nazwisko_kupującego>Strzalinski</nazwisko_kupującego>
		</kupujacy_podpis>
	</podpis>
	
</dokumenty_agencja>
